import React,{useState,useEffect} from 'react'
import {Card,Load,Form} from '../components'

const ShowCards = ({data,title})=>{
    if(data?.length > 0) {
        return data.map((post)=><Card key={post._id} {...post}/>)}

    return (
        <h2 className="mt-5 font-bold text-xl text-[#6449ff] uppercase">
            {title}
        </h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchInfo, setSearchInfo] = useState('');
    const [searchedResults, setSearchedResults] = useState(null)
    const [searchTimeout, setSearchTimeout] = useState(null)

    useEffect(()=>{
        const fetchPosts = async()=>{
            setLoading(true);
            try {
                const res = await fetch('http://localhost:8080/api/v1/post',{
                    method:'GET',
                    headers:{
                        'Content-Type' :'application/json'
                    }
                })

                if(res.ok){
                    const result = await res.json();
                    setAllPosts(result.data.reverse())
                }
            } catch (error) {
                
            }finally{
                setLoading(false);
            }
        }

        fetchPosts()
    },[])

    const handleSearch = (e)=>{
        clearTimeout(searchTimeout);
        setSearchInfo(e.target.value);
        setSearchTimeout(
        setTimeout(()=>{
            const searchResults = allPosts.filter((item)=> item.name.toLowerCase().includes(searchInfo.toLowerCase()) 
            || item.prompt.toLowerCase().includes(searchInfo.toLowerCase()));

            setSearchedResults(searchResults);
        },500));
    }
  return (
    <section className="max-w-7xl mx-auto">
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>
                The Community Showcase
            </h1>
            <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
                Browse through a collection of visually stunning images generated by DALL-E AI
            </p>
        </div>

        <div className="mt-16">
            <Form labelName="Search posts" type="text" name="text" placeholder="Search posts" value={searchInfo} handleChange={handleSearch}/>
        </div>
        <div className="mt-10">
            {loading?(
                <div className='flex justify-center items-center'>
                    <Load/>
                </div>
            ):(
                <>
                {searchInfo && (
                    <h2 className="font-medium text-[#666e75]
                    text-xl mb-3">
                        Showing results for <span className='text-[#222328]'>{searchInfo}</span>

                    </h2>
                )}
                <div className="grid lg:grid-cols-4 sm:grid-cols-3
                xs:grid-cols-2 grid-cols-1 gap-3">
                    {searchInfo ? (
                        <ShowCards data={searchedResults} title='No search results found'/>
                    ):(
                        <ShowCards data={allPosts} title="No posts found"/>
                    )}
                </div>
                </>
            )}
        </div>
    </section>
  )
}

export default Home